version: "3.8"

volumes:
  logs:
    driver: local

services:
  db:
    extends:
      file: ./docker/db/mysql.yml
      service: db

  adminer:
    extends:
      file: ./docker/db/adminer.yml
      service: adminer

  php:
    container_name: slim_php
    working_dir: /var/www
    command: php -S 0.0.0.0:8080 -t public
    build:
      context: ./docker/php
    ports:
      - "8080:8080"
    volumes:
      - .:/var/www
      - logs:/var/www/logs

  nginx:
    container_name: slim_nginx
    image: nginx:stable-alpine
    ports:
      - "12000:80"
    volumes:
      - .:/var/www/slim_app
      - ./docker/nginx/default.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - php
